$patch: replace
apiVersion: v1	
kind: Service	
metadata:	
  name: guestbook-ui	
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
spec:	
  ports:
  - port: 81	
    targetPort: 80	
  selector:	
    app: guestbook-ui
